"use strict";

module.exports.correos = require('./src/correosTracker')
module.exports.correosOld  = require('./src/correosOldTracker')
module.exports.sky = require('./src/skyTracker')
module.exports.adicional = require('./src/adicionalTracker')
module.exports.expresso24 = require('./src/expresso24Tracker')
module.exports.singpost = require('./src/singpostTracker')
module.exports.ctt = require('./src/cttTracker')
module.exports.cainiao = require('./src/cainiaoTracker')
module.exports.correoses = require('./src/correosESTracker')
module.exports.directlink = require('./src/directLink')
module.exports.trackchinapost = require('./src/trackChinaPost')
module.exports.postNL = require('./src/postNL')
module.exports.yanwen = require('./src/yanwen')
module.exports.malaysiaPos = require('./src/malaysiaPosTracker')
module.exports.cjah = require('./src/cjahTracker')
module.exports.winit = require('./src/winitTrack')
module.exports.panasia = require('./src/panasiaTracker')
module.exports.pitneybowes = require('./src/pitneybowesTracker')
module.exports.dhl = require('./src/dhlTracker')
module.exports.track24 = require('./src/track24')
module.exports.mrw = require('./src/mrwTracker')
module.exports.ips = require('./src/ipsTracker')
module.exports.track17 = require('./src/17track')
